accounts/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView,LogoutView
from accounts.forms import UserLoginForm,UserCreationForm
from accounts.views import RegisterView,UserprofileView

urlpatterns = [
    path('login/',LoginView.as_view(authentication_form=UserLoginForm),name='login'),
    path('register/',RegisterView.as_view(),name='register'),
    path('logout/',LogoutView.as_view(),name='logout'),
    path('profile/',UserprofileView.as_view(),name='profile'),
    path('',include('django.contrib.auth.urls'))
]

django_pm/urls.py
from django.contrib import admin
from django.urls import path, include
import debug_toolbar # type: ignore
from . import settings
urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('',include('projects.urls')),
    path('accounts/',include('accounts.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

projects/urls.py
from django.urls import path, include
from . import views
urlpatterns = [
    path('',views.ProjectList.as_view(),name='project_list'),
    path('project/create',views.CreateProjectView.as_view(),name='create_project'),
    path('project/edit/<int:pk>',views.UpdateProjectView.as_view(),name='update_project'),
    path('project/delete/<int:pk>',views.DeleteProjectView.as_view(),name='delete_project'),
    path('task/create',views.CreateTaskView.as_view(),name='create_task'),
    path('task/edit/<int:pk>',views.UpdateTaskView.as_view(),name='update_task'),
    path('task/delete/<int:pk>',views.DeleteTaskView.as_view(),name='delete_task'),
]

projects/models.py
from django.db import models
from django.conf.global_settings import AUTH_USER_MODEL
from django.utils.translation import gettext as _
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class ProjectStatus(models.IntegerChoices):
    PENDING = 1, _('Pending')
    COMPLETED = 2, _('Completed')
    POSTPONED = 3, _('Postponed')
    CANCELED = 4, _('Canceled')


class Project(models.Model):

    title = models.CharField(max_length=255)
    description = models.TextField()
    status = models.IntegerField(
        choices=ProjectStatus.choices,
        default=ProjectStatus.PENDING
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    category = models.ForeignKey(Category,on_delete=models.PROTECT,null=True)
    user = models.ForeignKey(AUTH_USER_MODEL,on_delete=models.CASCADE,null=True)

    def __str__(self):
        return self.title


class Task(models.Model):
    
    description = models.TextField()
    is_completed = models.BooleanField(default=False)
    project = models.ForeignKey(Project,on_delete=models.CASCADE)

    def __str__(self):
        return self.description

projects/forms.py
from django import forms
from projects.models import Project
from django.utils.translation import gettext as _
attrs={'class':'form-control','style':'margin: 10px;'}

class ProjectCreateForm(forms.ModelForm):
    
    class Meta:
        model = Project
        fields = ['title','description','category']
       
        widgets = {
            "category" : forms.Select(attrs=attrs),
            "title": forms.TextInput(attrs=attrs),
            "description": forms.Textarea(attrs=attrs),
        }

        labels = {
            "category" : _("Category"),
            "title" : _("title"),
            "description":_("description")
        }

        
class ProjectUpdateForm(forms.ModelForm):
    
    class Meta:
        model = Project
        fields = ['title','status','category']
        widgets = {
            "category": forms.Select(attrs=attrs),
            "title": forms.TextInput(attrs=attrs),
            "status" : forms.Select(attrs=attrs)

        }

projects/views.py
from django.db.models.query import QuerySet
from django.views.generic import ListView,CreateView,UpdateView,DeleteView
from projects.models import Project,Task
from projects.forms import ProjectCreateForm,ProjectUpdateForm
from django.urls import reverse_lazy,reverse
from django.shortcuts import redirect
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
class ProjectList(LoginRequiredMixin,ListView):
    model = Project
    template_name = 'projects/list.html'
    paginate_by = 3

    def get_queryset(self):
        query_set = super().get_queryset()
        where = {'user_id':self.request.user}

        q = self.request.GET.get('q',None)
        if q:
            where['title__icontains'] = q
        return query_set.filter(**where)


class CreateProjectView(LoginRequiredMixin,CreateView):
    model = Project
    form_class = ProjectCreateForm
    template_name = 'projects/create.html'
    success_url = reverse_lazy('project_list')

    def  form_valid(self, form):
        form.instance.user=self.request.user
        return super().form_valid(form)
    

class DeleteProjectView(LoginRequiredMixin,DeleteView):

    model = Project
    http_method_names=["post"]

    def get_success_url(self):
        return reverse('project_list')

class UpdateProjectView(LoginRequiredMixin,UserPassesTestMixin,UpdateView):
    model = Project
    form_class = ProjectUpdateForm
    template_name = 'projects/update.html'

    def test_func(self):
        return self.get_object().user_id == self.request.user.id
    
    def get_success_url(self):
        return reverse('update_project',args=[self.object.id])

class CreateTaskView(LoginRequiredMixin,UserPassesTestMixin,CreateView):
    model = Task
    fields = ['description','project']
    http_method_names = ['post']

    def test_func(self):
        project_id = self.request.POST.get('project','')
        return Project.objects.get(pk=project_id).user_id == self.request.user.id
    
    def get_success_url(self):
        return reverse('update_project',args=[self.object.project.id])

class UpdateTaskView(LoginRequiredMixin,UpdateView):
    model = Task
    fields = ['is_completed']
    http_method_names = ['post']

    def test_func(self):
        project_id = self.request.POST.get('project','')
        return Project.objects.get(pk=project_id).user_id == self.request.user.id

    def get_success_url(self):
        return reverse('update_project',args=[self.object.project.id])

class DeleteTaskView(LoginRequiredMixin,DeleteView):
    model = Task

    def test_func(self):
        project_id = self.request.POST.get('project','')
        return Project.objects.get(pk=project_id).user_id == self.request.user.id
        
    def get_success_url(self):
        return reverse('update_project',args=[self.object.project.id])

projects/templates/projects/create.html
{% extends 'base.html' %}
{% load i18n %}


{% block content %}

    <div class="container py-5 ">
        <div class="card bg-gradiant p-3">
            <h3 class="card-title">
                {% trans "New Project" %}
            </h3>

            <div class="card-body ">
                <form method="POST" action="{% url 'create_project'%}">
                    {% csrf_token %}
                    {% include "common/form.html" with form=form %}
                    <button class="btn bg-success text-white ">{% trans "Create" %} </button> 
                </form>
            </div>
        </div>
    </div>

{% endblock content %}

projects/templates/projects/list.html
{% extends 'base.html' %}
{% load i18n %}

{% load humanize %}
{% block content %}

    <div class="container">
        <div class="d-flex align-items-center justify-content-center ">
            <h3 class="my-5 me-auto"> {% trans "My projects" %} </h3>
            <div class="btn btn-outline-success"> 
                <i class="bi bi-plus-lg"></i>
                <a class="text-success text-decoration-none" href="{% url 'create_project' %}">
                    {% trans 'New Project' %}
                </a>
            </div>
        </div>

        <div class="row h-100"> 
            {% for project in object_list%}
            <div class="col-lg-4 col-md-6">
                <div class = "card" >
                    <div class = "card-body " >
                        <span class="badge text-light bg-dark rounded-pill p-2"> 
                            {{project.get_status_display}}
                        </span>
                        <div class="card-title my-2"> 
                            {{project.title}}
                        </div>
                        <div class="card-title text-black-50"> 
                            {{project.description}}
                        </div>
                        <div class="details d-flex ">
                            <time class="me-auto" datetime="{{project.created_at}}">
                                {{project.created_at|naturaltime}}
                            </time>
                            <div class="editing">
                                <a href="{% url 'update_project' project.id %}" class=" btn btn-outline-dark me-3 btn-sm">
                                    {% trans 'Edit' %}
                                </a>
                                <form action="{% url 'delete_project' project.id %}" method="post" style="display:inline;">
                                    {% csrf_token %}
                                    <button type="submit" class="btn-outline-danger btn btn-sm">
                                        <i class="bi bi-trash"></i>
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {%empty %}

            <div class="main col-12 border bg-white rounded-3 text-center p-5">
                <p class="">{% trans 'There are No projects to Show' %} </p>
                <span> <i class="bi bi-emoji-frown d-block fs-1 p-3"></i> </span>
                <div class="btn btn-outline-success"> 
                    <i class="bi bi-plus-lg"></i>
                    <a class="text-success text-decoration-none" href="{% url 'create_project' %}">
                        {% trans 'New Project' %}
                    </a>
                </div>
            </div>
            {%endfor%}

            {% if page_obj.paginator.count > 0 %}
                <div class="">
                    
                    <nav>
                        <ul class="paginations d-flex justify-content-center my-3 list-unstyled">
                            {% if page_obj.has_previous %}
                                <li class="page-item"> 
                                    <a class="page-link" href="?page={{page_obj.previous_page_number}}"> {% trans 'Previous' %} </a>
                                </li>
                            {% else %}
                                <li class="page-item disabled"> 
                                    <a class="page-link " href="#"> {% trans 'Previous' %} </a>
                                </li>
            
                            {% endif %}

                            {% if page_obj.has_next %}
                                <li class="page-item"> 
                                    <a class="page-link" href="?page={{page_obj.next_page_number}}"> {% trans "Next" %} </a>
                                </li>
                            {% else %}
                                <li class="page-item disabled"> 
                                    <a class="page-link " href="#"> {% trans "Next" %} </a>
                                </li>
            
                            {% endif %}
                        </ul>
                    </nav>

                </div>
                    
            {%endif%}
        </div>
    </div>

    

{% endblock content %}

projects/templates/projects/task.html
{% load i18n %}



<ul class="list-unstyled">
    {% for task in project.task_set.all %}
    <li class="d-flex list-group-item justify-content-center align-items-center"> 
    <form method="post"  action="{% url 'update_task' task.id %}" >
        {% csrf_token %}
        <input
            type='checkbox'
            name='is_completed'
            {% if task.is_completed %} checked {%endif%}
             onchange="this.form.submit()" />
        {{task.description}}
    </form>
    <form class="ms-auto" method="post" action="{% url 'delete_task' task.id %}" >
        {% csrf_token %}
        <button type="submit" class="btn btn-danger"> <i class="bi bi-trash "></i> </button>
    </form>
        </li>
    {%endfor%}
</ul>

<form class="d-flex" method="post" action="{% url 'create_task' %}" >
    {% csrf_token %}
    <input type='hidden' value={{project.id}} name='project'/>
    <input class="form-control" type='text' name='description' placeholder="New Task"/>
    <input type='submit' value='add' class="bg-success text-light "/>
</form>

projects/templates/projects/update.html
{% extends 'base.html' %}
{% load i18n %}



{% block content %}
    <div class="container">
    <h5 class="mt-5 text-black-50"> {{object.title}} </h5>

    <div class="row">
        <div class="col-4">
            
            <form class="mb-2 " method="post" action="{% url 'update_project' object.id %}" >
                {% csrf_token %}

            <div class="card container-fluid">
                <ul class="list-unstyled">
                    {% for field in form  %}
                    <li class="container-fluid"> {{field}} </li>
                {% endfor %}
                <time class="ms-4" datetime="{{object.created_at}}">
                   <i class="bi bi-clock me-2"></i> {{object.created_at}}
                </time>
                </ul>
                    <button  type="submit" class="btn btn-success w-100 mb-2"> <i class="bi bi-box-arrow-down"></i> {% trans 'Save' %}</button>
                </form>
                <form class="mb-2 " method="post" action="{% url 'delete_project' object.id %}" >
                    {% csrf_token %}
                    <button  type="submit" class="btn btn-danger w-100 mb-2"> <i class="bi bi-trash "></i> {% trans "Delete" %}</button>
                </form>

            </div>

        </div>
        <div class="col-8">
                {% include "projects/task.html" with project=object %}
        </div>
    </div>
    </div>
{% endblock content %}